/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonText: typeof import('./src/components/ButtonText.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    FileUploadBlock: typeof import('./src/components/FileUploadBlock.vue')['default']
    FileUploadButton: typeof import('./src/components/FileUploadButton.vue')['default']
    HeroImage: typeof import('./src/components/HeroImage.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InputAnnouncement: typeof import('./src/components/InputAnnouncement.vue')['default']
    InputCheckbox: typeof import('./src/components/InputCheckbox.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    InputSlider: typeof import('./src/components/InputSlider.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    SlideshowUploadSection: typeof import('./src/components/sections/SlideshowUploadSection.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TimetableUploadSection: typeof import('./src/components/sections/TimetableUploadSection.vue')['default']
    TmsXmlUploadSection: typeof import('./src/components/sections/TmsXmlUploadSection.vue')['default']
    VoicesSelector: typeof import('./src/components/VoicesSelector.vue')['default']
  }
}
