/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Chip: typeof import('./src/components/ui/Chip.vue')['default']
    ColsBuilder: typeof import('./src/components/ui/ColsBuilder.vue')['default']
    ContextMenu: typeof import('./src/components/ui/ContextMenu.vue')['default']
    FileUploadBlock: typeof import('./src/components/ui/FileUploadBlock.vue')['default']
    FileUploadButton: typeof import('./src/components/ui/FileUploadButton.vue')['default']
    HeroImage: typeof import('./src/components/ui/HeroImage.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    InputCheckbox: typeof import('./src/components/ui/InputCheckbox.vue')['default']
    InputDate: typeof import('./src/components/ui/InputDate.vue')['default']
    InputGroup: typeof import('./src/components/ui/InputGroup.vue')['default']
    InputSwitch: typeof import('./src/components/ui/InputSwitch.vue')['default']
    InvokableModalDialog: typeof import('./src/components/ui/InvokableModalDialog.vue')['default']
    ModalDialog: typeof import('./src/components/ui/ModalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    SidePanel: typeof import('./src/components/ui/SidePanel.vue')['default']
    Tab: typeof import('./src/components/ui/Tab.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
  }
}
