/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./src/components/ButtonPrimary.vue')['default']
    ButtonText: typeof import('./src/components/ButtonText.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DropZone: typeof import('./src/components/DropZone.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InputCheckbox: typeof import('./src/components/InputCheckbox.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    InputSlider: typeof import('./src/components/InputSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TmsScheduleUploadSection: typeof import('./src/components/TmsScheduleUploadSection.vue')['default']
    TmsXmlUploadSection: typeof import('./src/components/TmsXmlUploadSection.vue')['default']
  }
}
